kind = "web"
previewPath = "/mindwellness/"
title = "MindWellness (MW)"
version = "1.0.0"
id = "artifacts/mindwellness"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 20677
name = "web"
paths = ["/mindwellness/"]

[services.development]
run = "pnpm --filter @workspace/mindwellness run dev"

[services.env]
PORT = "20677"
BASE_PATH = "/mindwellness/"

[services.production]
build = ["pnpm", "--filter", "@workspace/mindwellness", "run", "build"]
publicDir = "artifacts/mindwellness/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
